# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: aws-util

provider:
  name: aws
  runtime: python3.7
  region: us-west-2

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds:StartDBInstance"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rds:StopDBInstance"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rds:DescribeDBInstances"
      Resource: "*"

functions:
  startStopRDS:
    handler: handler.start_stop_rds
    events:
      - schedule:
          name: shutdown-rds
          description: 'At 10pm PDT shutdown RDS instances. (AWS is UTC obviously)'
          # https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
          rate: cron(0 5 * * ? *)
          input:
            action: stop
      - schedule:
          name: start-rds
          description: 'At 9am PDT start RDS instances. (AWS is UTC obviously)'
          # https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html
          rate: cron(0 6 * * ? *)
          input:
            action: start

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
